/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtikelRouteImport } from './routes/artikel'
import { Route as BeritaRouteImport } from './routes/berita'
import { Route as CabangRouteImport } from './routes/cabang'
import { Route as CheckupRouteImport } from './routes/checkup'
import { Route as FasilitasRouteImport } from './routes/fasilitas'
import { Route as GaleriRouteImport } from './routes/galeri'
import { Route as HargaRouteImport } from './routes/harga'
import { Route as LayananRouteImport } from './routes/layanan'
import { Route as LegalitasRouteImport } from './routes/legalitas'
import { Route as ReservasiRouteImport } from './routes/reservasi'
import { Route as ArtikelSlugRouteImport } from './routes/artikel_.$slug'
import { Route as BeritaSlugRouteImport } from './routes/berita_.$slug'
import { Route as HasilKodeRouteImport } from './routes/hasil_.$kode'
import { Route as ValidasiKodeRouteImport } from './routes/validasi_.$kode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelRoute = ArtikelRouteImport.update({
  id: '/artikel',
  path: '/artikel',
  getParentRoute: () => rootRouteImport,
} as any)
const BeritaRoute = BeritaRouteImport.update({
  id: '/berita',
  path: '/berita',
  getParentRoute: () => rootRouteImport,
} as any)
const CabangRoute = CabangRouteImport.update({
  id: '/cabang',
  path: '/cabang',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckupRoute = CheckupRouteImport.update({
  id: '/checkup',
  path: '/checkup',
  getParentRoute: () => rootRouteImport,
} as any)
const FasilitasRoute = FasilitasRouteImport.update({
  id: '/fasilitas',
  path: '/fasilitas',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriRoute = GaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const HargaRoute = HargaRouteImport.update({
  id: '/harga',
  path: '/harga',
  getParentRoute: () => rootRouteImport,
} as any)
const LayananRoute = LayananRouteImport.update({
  id: '/layanan',
  path: '/layanan',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalitasRoute = LegalitasRouteImport.update({
  id: '/legalitas',
  path: '/legalitas',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservasiRoute = ReservasiRouteImport.update({
  id: '/reservasi',
  path: '/reservasi',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelSlugRoute = ArtikelSlugRouteImport.update({
  id: '/artikel_/$slug',
  path: '/artikel/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BeritaSlugRoute = BeritaSlugRouteImport.update({
  id: '/berita_/$slug',
  path: '/berita/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HasilKodeRoute = HasilKodeRouteImport.update({
  id: '/hasil_/$kode',
  path: '/hasil/$kode',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidasiKodeRoute = ValidasiKodeRouteImport.update({
  id: '/validasi_/$kode',
  path: '/validasi/$kode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artikel': typeof ArtikelRoute
  '/berita': typeof BeritaRoute
  '/cabang': typeof CabangRoute
  '/checkup': typeof CheckupRoute
  '/fasilitas': typeof FasilitasRoute
  '/galeri': typeof GaleriRoute
  '/harga': typeof HargaRoute
  '/layanan': typeof LayananRoute
  '/legalitas': typeof LegalitasRoute
  '/reservasi': typeof ReservasiRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/berita/$slug': typeof BeritaSlugRoute
  '/hasil/$kode': typeof HasilKodeRoute
  '/validasi/$kode': typeof ValidasiKodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artikel': typeof ArtikelRoute
  '/berita': typeof BeritaRoute
  '/cabang': typeof CabangRoute
  '/checkup': typeof CheckupRoute
  '/fasilitas': typeof FasilitasRoute
  '/galeri': typeof GaleriRoute
  '/harga': typeof HargaRoute
  '/layanan': typeof LayananRoute
  '/legalitas': typeof LegalitasRoute
  '/reservasi': typeof ReservasiRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/berita/$slug': typeof BeritaSlugRoute
  '/hasil/$kode': typeof HasilKodeRoute
  '/validasi/$kode': typeof ValidasiKodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artikel': typeof ArtikelRoute
  '/berita': typeof BeritaRoute
  '/cabang': typeof CabangRoute
  '/checkup': typeof CheckupRoute
  '/fasilitas': typeof FasilitasRoute
  '/galeri': typeof GaleriRoute
  '/harga': typeof HargaRoute
  '/layanan': typeof LayananRoute
  '/legalitas': typeof LegalitasRoute
  '/reservasi': typeof ReservasiRoute
  '/artikel_/$slug': typeof ArtikelSlugRoute
  '/berita_/$slug': typeof BeritaSlugRoute
  '/hasil_/$kode': typeof HasilKodeRoute
  '/validasi_/$kode': typeof ValidasiKodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artikel'
    | '/berita'
    | '/cabang'
    | '/checkup'
    | '/fasilitas'
    | '/galeri'
    | '/harga'
    | '/layanan'
    | '/legalitas'
    | '/reservasi'
    | '/artikel/$slug'
    | '/berita/$slug'
    | '/hasil/$kode'
    | '/validasi/$kode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artikel'
    | '/berita'
    | '/cabang'
    | '/checkup'
    | '/fasilitas'
    | '/galeri'
    | '/harga'
    | '/layanan'
    | '/legalitas'
    | '/reservasi'
    | '/artikel/$slug'
    | '/berita/$slug'
    | '/hasil/$kode'
    | '/validasi/$kode'
  id:
    | '__root__'
    | '/'
    | '/artikel'
    | '/berita'
    | '/cabang'
    | '/checkup'
    | '/fasilitas'
    | '/galeri'
    | '/harga'
    | '/layanan'
    | '/legalitas'
    | '/reservasi'
    | '/artikel_/$slug'
    | '/berita_/$slug'
    | '/hasil_/$kode'
    | '/validasi_/$kode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtikelRoute: typeof ArtikelRoute
  BeritaRoute: typeof BeritaRoute
  CabangRoute: typeof CabangRoute
  CheckupRoute: typeof CheckupRoute
  FasilitasRoute: typeof FasilitasRoute
  GaleriRoute: typeof GaleriRoute
  HargaRoute: typeof HargaRoute
  LayananRoute: typeof LayananRoute
  LegalitasRoute: typeof LegalitasRoute
  ReservasiRoute: typeof ReservasiRoute
  ArtikelSlugRoute: typeof ArtikelSlugRoute
  BeritaSlugRoute: typeof BeritaSlugRoute
  HasilKodeRoute: typeof HasilKodeRoute
  ValidasiKodeRoute: typeof ValidasiKodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel': {
      id: '/artikel'
      path: '/artikel'
      fullPath: '/artikel'
      preLoaderRoute: typeof ArtikelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berita': {
      id: '/berita'
      path: '/berita'
      fullPath: '/berita'
      preLoaderRoute: typeof BeritaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabang': {
      id: '/cabang'
      path: '/cabang'
      fullPath: '/cabang'
      preLoaderRoute: typeof CabangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkup': {
      id: '/checkup'
      path: '/checkup'
      fullPath: '/checkup'
      preLoaderRoute: typeof CheckupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fasilitas': {
      id: '/fasilitas'
      path: '/fasilitas'
      fullPath: '/fasilitas'
      preLoaderRoute: typeof FasilitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeri': {
      id: '/galeri'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof GaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harga': {
      id: '/harga'
      path: '/harga'
      fullPath: '/harga'
      preLoaderRoute: typeof HargaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layanan': {
      id: '/layanan'
      path: '/layanan'
      fullPath: '/layanan'
      preLoaderRoute: typeof LayananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legalitas': {
      id: '/legalitas'
      path: '/legalitas'
      fullPath: '/legalitas'
      preLoaderRoute: typeof LegalitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservasi': {
      id: '/reservasi'
      path: '/reservasi'
      fullPath: '/reservasi'
      preLoaderRoute: typeof ReservasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel_/$slug': {
      id: '/artikel_/$slug'
      path: '/artikel/$slug'
      fullPath: '/artikel/$slug'
      preLoaderRoute: typeof ArtikelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berita_/$slug': {
      id: '/berita_/$slug'
      path: '/berita/$slug'
      fullPath: '/berita/$slug'
      preLoaderRoute: typeof BeritaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hasil_/$kode': {
      id: '/hasil_/$kode'
      path: '/hasil/$kode'
      fullPath: '/hasil/$kode'
      preLoaderRoute: typeof HasilKodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validasi_/$kode': {
      id: '/validasi_/$kode'
      path: '/validasi/$kode'
      fullPath: '/validasi/$kode'
      preLoaderRoute: typeof ValidasiKodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtikelRoute: ArtikelRoute,
  BeritaRoute: BeritaRoute,
  CabangRoute: CabangRoute,
  CheckupRoute: CheckupRoute,
  FasilitasRoute: FasilitasRoute,
  GaleriRoute: GaleriRoute,
  HargaRoute: HargaRoute,
  LayananRoute: LayananRoute,
  LegalitasRoute: LegalitasRoute,
  ReservasiRoute: ReservasiRoute,
  ArtikelSlugRoute: ArtikelSlugRoute,
  BeritaSlugRoute: BeritaSlugRoute,
  HasilKodeRoute: HasilKodeRoute,
  ValidasiKodeRoute: ValidasiKodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
